/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    hero: HeroBlock;
    richText: RichTextBlock;
    mediaBlock: MediaBlockType;
    cta: CtaBlock;
    productRail: ProductRailBlock;
    categoryGrid: CategoryGridBlock;
    landersExperience: LandersExperienceBlock;
    cartBestsellerRail: CartBestsellerRailBlock;
    reusableContent: ReusableContentBlock;
    documentSlot: DocumentSlotBlock;
  };
  collections: {
    pages: Page;
    'product-content': ProductContent;
    'reusable-content': ReusableContent;
    'page-templates': PageTemplate;
    banners: Banner;
    sales: Sale;
    media: Media;
    users: User;
    redirects: Redirect;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'product-content': ProductContentSelect<false> | ProductContentSelect<true>;
    'reusable-content': ReusableContentSelect<false> | ReusableContentSelect<true>;
    'page-templates': PageTemplatesSelect<false> | PageTemplatesSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    sales: SalesSelect<false> | SalesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    'secondary-header': SecondaryHeader;
    footer: Footer;
    'bottom-nav': BottomNav;
    'right-rail': RightRail;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    'secondary-header': SecondaryHeaderSelect<false> | SecondaryHeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'bottom-nav': BottomNavSelect<false> | BottomNavSelect<true>;
    'right-rail': RightRailSelect<false> | RightRailSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  subheading?: string | null;
  image?: (number | null) | Media;
  alignment?: ('left' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility text. Required.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  media: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  body?: string | null;
  label: string;
  href: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductRailBlock".
 */
export interface ProductRailBlock {
  /**
   * e.g. "Grand Grocery Sale", "On Sale".
   */
  title: string;
  /**
   * Products themselves are Medusa-driven — this only names the rail and which Medusa collection/category it pulls from.
   */
  medusaCollectionId: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productRail';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  /**
   * docs/10 §5.4 Category/Department Highlight Grid.
   */
  tiles?:
    | {
        /**
         * Required.
         */
        image?: {
          desktopImage?: (number | null) | Media;
          mobileImage?: (number | null) | Media;
          /**
           * Accessibility text for the image.
           */
          alt?: string | null;
        };
        tagline?: string | null;
        slug: string;
        medusaTargetId: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LandersExperienceBlock".
 */
export interface LandersExperienceBlock {
  /**
   * docs/10 §5.5 "Story Card" — image, title, video link.
   */
  items?:
    | {
        /**
         * Required.
         */
        image?: {
          desktopImage?: (number | null) | Media;
          mobileImage?: (number | null) | Media;
          /**
           * Accessibility text for the image.
           */
          alt?: string | null;
        };
        title: string;
        videoLink: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'landersExperience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CartBestsellerRailBlock".
 */
export interface CartBestsellerRailBlock {
  /**
   * Which SoW rail this is — ranking is computed separately per scope.
   */
  scope: '1p' | '3p';
  /**
   * e.g. "Bestsellers".
   */
  title: string;
  /**
   * Trailing order-frequency window the Medusa worker ranks over.
   */
  computationWindowDays?: number | null;
  /**
   * How often the worker recomputes the ranking.
   */
  updateFrequencyDays?: number | null;
  /**
   * Manually pin specific SKUs ahead of the computed ranking, regardless of computed rank (F-100/F-101). Order here is pin order.
   */
  pinnedProducts?:
    | {
        medusaProductId: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cartBestsellerRail';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReusableContentBlock".
 */
export interface ReusableContentBlock {
  source: number | ReusableContent;
  /**
   * On: renders the source live, so edits there appear here. Off: takes a one-time copy you can edit independently.
   */
  useSourceValues?: boolean | null;
  content?: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reusableContent';
}
/**
 * Content authored once and referenced from documents in any collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content".
 */
export interface ReusableContent {
  id: number;
  title: string;
  content: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DocumentSlotBlock".
 */
export interface DocumentSlotBlock {
  slot: 'main' | 'extra';
  id?: string | null;
  blockName?: string | null;
  blockType: 'documentSlot';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment, e.g. "about-us".
   */
  slug: string;
  /**
   * Copied into the layout below when the page is first created.
   */
  contentTemplate?: (number | null) | PageTemplate;
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | MediaBlockType
        | CtaBlock
        | ReusableContentBlock
        | ProductRailBlock
        | CategoryGridBlock
        | LandersExperienceBlock
        | CartBestsellerRailBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Layouts shared by a whole kind of page. Add a Document Slot block where each page’s own content should appear.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates".
 */
export interface PageTemplate {
  id: number;
  name: string;
  appliesTo: 'pages' | 'product-content';
  /**
   * Resolve at read: editing this template changes every document using it, and they cannot edit the shared sections. Copy on create: new documents get these blocks as a starting point and own them from then on.
   */
  strategy: 'resolveAtRead' | 'copyOnCreate';
  layout: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock | ReusableContentBlock | DocumentSlotBlock)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editorial enrichment for a Medusa product. Price, stock and the canonical product name live in Medusa and are rejected here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-content".
 */
export interface ProductContent {
  id: number;
  /**
   * The join key to Medusa. The only commerce identifier Payload stores.
   */
  medusaProductId: string;
  /**
   * Editorial display copy. NOT the canonical product name -- that stays in Medusa.
   */
  marketingName: string;
  shortDescription?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * The layout shared by this kind of product page. Its sections are resolved on read — edit the template to change every product using it.
   */
  contentTemplate?: (number | null) | PageTemplate;
  /**
   * Fills the template's 'Extra' slot. For the one product that needs something the shared layout does not provide.
   */
  templateOverrides?: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock | ReusableContentBlock)[] | null;
  templateApplied?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The template's shared sections with this product's own blocks spliced in.
   */
  resolvedDetail?: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock | ReusableContentBlock)[] | null;
  /**
   * Sections unique to this product. Sections shared across every product come from its template (Phase 3).
   */
  productDetail?: (HeroBlock | RichTextBlock | MediaBlockType | CtaBlock | ReusableContentBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hero Carousel, Standalone Campaign Banner, PLP, Sticky Sale Bar — where a banner shows is set in Placements below. The Right Rail is assigned separately (Globals → Right Rail); the Footer's app-download banner is a field on Globals → Footer, not a Banners document at all.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * Editor-facing label. Not shown to customers.
   */
  internalTitle: string;
  /**
   * Required.
   */
  creative?: {
    mediaType?: ('image' | 'video') | null;
    desktopImage?: (number | null) | Media;
    mobileImage?: (number | null) | Media;
    /**
     * Accessibility text for the image.
     */
    alt?: string | null;
    desktopVideo?: (number | null) | Media;
    mobileVideo?: (number | null) | Media;
    controls?: boolean | null;
    autoplay?: boolean | null;
    desktopPoster?: (number | null) | Media;
    mobilePoster?: (number | null) | Media;
  };
  link?: {
    url?: string | null;
    target?: ('same' | 'new') | null;
  };
  /**
   * Leave blank to show as soon as published.
   */
  startDate?: string | null;
  /**
   * Leave blank for no end date.
   */
  endDate?: string | null;
  /**
   * Optional — link a Sale so this banner can show a live countdown to its end date.
   */
  sale?: (number | null) | Sale;
  /**
   * Render a live countdown to the linked Sale's end date on this banner.
   */
  showCountdown?: boolean | null;
  /**
   * Where this banner appears. F-056's "Multiple placements" — one banner can occupy more than one surface at once.
   */
  placements: {
    surface: 'home-hero' | 'home-standalone' | 'plp' | 'sticky-bar';
    /**
     * The Medusa category, collection, or subcategory ID this banner is scoped to. Leave blank to show on every PLP — open question, docs/11-banner-specifications.md §7.
     */
    medusaCategoryId?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A sale/campaign window. Banners link here for a synced countdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales".
 */
export interface Sale {
  id: number;
  /**
   * e.g. "9 FOR ₱9 — Sept 2026". Not shown to customers.
   */
  internalTitle: string;
  startDate: string;
  /**
   * Every linked banner's countdown reads this value.
   */
  endDate: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The six admin roles named in the SoW. Only IT/Engineering can change this.
   */
  role: 'contentManager' | 'csAgent' | 'operations' | 'finance' | 'engineering' | 'leadership';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Old URL -> new URL. Populate from the Magento URL map before cutover so search rankings survive the replatform.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'product-content';
          value: number | ProductContent;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable record of every content change: who, what, when, and the before/after of each field. Entries cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  summary?: string | null;
  /**
   * Null for system operations (seeds, migrations).
   */
  user?: (number | null) | User;
  /**
   * Captured at write time so the trail survives the user being deleted.
   */
  userEmail?: string | null;
  operation: 'create' | 'update' | 'delete';
  collectionSlug: string;
  documentId: string;
  /**
   * The document's title at the time, so a deleted document is still identifiable.
   */
  documentLabel?: string | null;
  /**
   * Field names only — queryable without parsing the diff.
   */
  changedFields?: string[] | null;
  /**
   * Per field: { from, to }. On create, the created values. On delete, the last known values.
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP, user agent, and whether the change was an autosave.
   */
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'product-content';
        value: number | ProductContent;
      } | null)
    | ({
        relationTo: 'reusable-content';
        value: number | ReusableContent;
      } | null)
    | ({
        relationTo: 'page-templates';
        value: number | PageTemplate;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'sales';
        value: number | Sale;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contentTemplate?: T;
  layout?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-content_select".
 */
export interface ProductContentSelect<T extends boolean = true> {
  medusaProductId?: T;
  marketingName?: T;
  shortDescription?: T;
  heroImage?: T;
  contentTemplate?: T;
  templateOverrides?: T | {};
  templateApplied?: T;
  resolvedDetail?: T | {};
  productDetail?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content_select".
 */
export interface ReusableContentSelect<T extends boolean = true> {
  title?: T;
  content?: T | {};
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-templates_select".
 */
export interface PageTemplatesSelect<T extends boolean = true> {
  name?: T;
  appliesTo?: T;
  strategy?: T;
  layout?: T | {};
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  internalTitle?: T;
  creative?:
    | T
    | {
        mediaType?: T;
        desktopImage?: T;
        mobileImage?: T;
        alt?: T;
        desktopVideo?: T;
        mobileVideo?: T;
        controls?: T;
        autoplay?: T;
        desktopPoster?: T;
        mobilePoster?: T;
      };
  link?:
    | T
    | {
        url?: T;
        target?: T;
      };
  startDate?: T;
  endDate?: T;
  sale?: T;
  showCountdown?: T;
  placements?:
    | T
    | {
        surface?: T;
        medusaCategoryId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales_select".
 */
export interface SalesSelect<T extends boolean = true> {
  internalTitle?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  summary?: T;
  user?: T;
  userEmail?: T;
  operation?: T;
  collectionSlug?: T;
  documentId?: T;
  documentLabel?: T;
  changedFields?: T;
  changes?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide top navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  searchPlaceholder?: string | null;
  membershipCta: {
    label?: string | null;
    url: string;
  };
  /**
   * e.g. Help, Track Orders.
   */
  utilityLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The utility link row below the main header nav.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secondary-header".
 */
export interface SecondaryHeader {
  id: number;
  links: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide footer, including the "Download the App" banner directly above the link columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  appDownloadBanner?: {
    backgroundImage?: (number | null) | Media;
    appPreviewImage?: (number | null) | Media;
    logo?: (number | null) | Media;
    heading?: string | null;
    subheading?: string | null;
    qrCode?: (number | null) | Media;
    appStoreUrl?: string | null;
    googlePlayUrl?: string | null;
  };
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Leave blank to render this row as plain informational text rather than a link — e.g. "Store Business Hours," "Manila Stores: 9am - 9pm" in the Contact Us column.
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('Facebook' | 'Instagram' | 'YouTube' | 'TikTok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Visa, Mastercard, Amex, JCB, GCash, Maya, BDO, Cash on Delivery.
   */
  paymentMethods?:
    | {
        label: string;
        icon: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. SnapMart, Grab, Lalamove, AllEasy.
   */
  deliveryServices?:
    | {
        label: string;
        icon: number | Media;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Mobile-only bottom tab bar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bottom-nav".
 */
export interface BottomNav {
  id: number;
  items: {
    label: string;
    icon?: (number | null) | Media;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Desktop-only sidebar banners, shown on Home and PLP alike. Order here is display order, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "right-rail".
 */
export interface RightRail {
  id: number;
  /**
   * Drag to reorder.
   */
  banners?: (number | Banner)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  searchPlaceholder?: T;
  membershipCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  utilityLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secondary-header_select".
 */
export interface SecondaryHeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  appDownloadBanner?:
    | T
    | {
        backgroundImage?: T;
        appPreviewImage?: T;
        logo?: T;
        heading?: T;
        subheading?: T;
        qrCode?: T;
        appStoreUrl?: T;
        googlePlayUrl?: T;
      };
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  paymentMethods?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  deliveryServices?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bottom-nav_select".
 */
export interface BottomNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        icon?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "right-rail_select".
 */
export interface RightRailSelect<T extends boolean = true> {
  banners?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'product-content';
          value: number | ProductContent;
        } | null)
      | ({
          relationTo: 'reusable-content';
          value: number | ReusableContent;
        } | null)
      | ({
          relationTo: 'page-templates';
          value: number | PageTemplate;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}